[package]
name = "evm"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
tower = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

shared = { path = "../shared" }
